### ISSUE TITLE
balls

### ISSUE THREAD

**Issue by krampuszc** [CSRobloxCN/cs.roblox.cn#1]
cs.roblox.cn literally public lol
![image](https://github.com/CSRobloxCN/cs.roblox.cn/assets/54174182/7f95a75b-928c-4307-b0e0-254152c33528)

**Comment by interstellar-tars** [comment]
How- wha- do you just know everyone's Okta password?

**Comment by EasternBloxxer** [comment]
> How- wha- do you just know everyone's Okta password?

you don't need okta to see the frontend source are you retarded

**Comment by interstellar-tars** [comment]
No, but you are.

**Comment by EasternBloxxer** [comment]
> No, but you are.

I think you are buddy.
